RunConfig:
  Name: OPERA-TROPO-PGE-INT-TEST-RUNCONFIG
  Groups:
    PGE:
      PGENameGroup:
        PGEName: TROPO_PGE
      InputFilesGroup:
        InputFilePaths:
        - /home/ops/input_dir/ECMWF_TROP_202402151200_202402151200_1.nc
      DynamicAncillaryFilesGroup:
        AncillaryFileMap: {}
      ProductPathGroup:
        OutputProductPath: /home/ops/output_dir 
        ScratchPath: /home/ops/scratch_dir
      PrimaryExecutable:
        ProductIdentifier: TROPO
        ProductVersion: "0.2"
        ProgramPath: opera_tropo
        ProgramOptions:
        - run
        ErrorCodeBase: 800000
        SchemaPath: /home/ops/opera/pge/tropo/schema/tropo_sas_schema.yaml
        AlgorithmParametersSchemaPath: 
        IsoMeasuredParameterDescriptions:
        DataValidityStartDate:
        IsoTemplatePath: ""
      QAExecutable:
        Enabled: true
        ProgramPath: /home/ops/opera/.ci/scripts/tropo/compare_tropo_products.sh
        ProgramOptions: []
      DebugLevelGroup:
        DebugSwitch: false
        ExecuteViaShell: true
    SAS:
      input_file:
        # REQUIRED: path to HRES model file.
        #   Type: string | Path.
        input_file_path: /home/ops/input_dir/ECMWF_TROP_202402151200_202402151200_1.nc
      primary_executable:
        # Product type of the PGE.
        #   Type: string.
        product_type: OPERA_TROPO
      product_path_group:
        # REQUIRED: Directory where PGE will place results.
        #   Type: string.
        product_path: /home/ops/output_dir
        # Path to the scratch directory.
        #   Type: string.
        scratch_path: /home/ops/scratch_dir
        # Path to the SAS output directory.
        #   Type: string.
        sas_output_path: /home/ops/output_dir
        # Version of the product, in <major>.<minor> format.
        #   Type: string.
        product_version: '0.2'
      worker_settings:
        # Number of workers to run in parallel 
        #   Type: integer.
        n_workers: 4
        # Number of threads to use per worker. This sets the OMP_NUM_THREADS environment variable in
        #   each python process.
        #   Type: integer.
        threads_per_worker: 2
        # Max memory to use per worker in GB. 
        #   Type: integer.
        max_memory: 8
        # Dask local spill directory 
        #   Type: string.
        dask_temp_dir: tmp
        # Size (rows, columns) of blocks of data to load at a time.
        #   Type: array.
        block_shape:
          - 128
          - 128
      output_options:
        # Ouput chunks (time, height, lat, lon).
        #   Type: array.
        chunk_size:
          - 1
          - 64
          - 64
          - 64
        # Output height levels for ZTD, if empty use default HRES 145 levels.
        #   Type: list.
        output_heights: []
        # Level of compression applied to netcdf
        #   Type: dict.
        compression_kwargs:
          zlib: true
          complevel: 5
          shuffle: true
      # Path to the output log file in addition to logging to stderr.
      #   Type: string | null.
      log_file: output_dir/test_log.log