name: PGE Release
description: PGE Release Procedure
title: "<PGE Name> PGE <Release Version> Release"
labels: ["must have"]
body:
  - type: textarea
    id: procedure-steps
    attributes:
      label: PGE Release Procedure Steps
      description: Tailor the following task list as-necessary for the PGE Release to be performed
      value: |
          - [ ] Ensure `main` branch is up-to-date, then create the `release/<version>` branch off of it
          - [ ] Update [one of] the following version numbers:
            - In `src/opera/pge/<pge name>/<pge_name>_pge.py` update PGE_VERSION to `<version>`
            - In `src/opera/_package.py` update the "repository" version to `<version>`
          - [ ] Rename `examples/<pge name>_sample_runconfig-v<previous version>.yaml` to `examples/<pge name>_sample_runconfig-v<version>.yaml`
            - Ensure the version referenced in the comment at the top of the file is also updated
          - [ ] Push the `release/<version>` branch to `origin`, then execute the integration test for <PGE Name> within the Jenkins Int Test pipeline
            - If the branch does not show up in the Jenkins pipeline, use the "Scan Repository Now" feature of Jenkins to refresh list of avaialble branches
            - Once the Integration test is complete, inspect the results of the .html product comparison report to ensure all tests are passing
          - [ ] Run the Release pipeline in Jenkins to push the container images to Artifactory
            - See above note if the release branch does not show up in the list of available branches within the Jenkins Release Pipeline
            - If the version number within `src/opera/_package.py` was changed by this release, then ensure the "Publish Docs" option within the Release Pipeline is selected. Otherwise deselect it
          - [ ] Create a PR for the release branch. 
            - If there have been no major changes to the code (aside from version number updates), the branch can be merged immediately without review
          - [ ] Pull the merged branch back into your local checkout of `main`, then tag the latest commit as `<version>` and push the tag to `origin`
          - [ ] Create the github release page using the new tag
          - [ ] Update the ICS document for the new release, and upload to Artifactory, along with the latest example RunConfig
          - [ ] Send an email to the `operasds-all` mailing list containing details of the release and links to the released artifacts (docker image, ICS doc, etc.)
    validations:
      required: true
