# Dockerfile to produce the production DSWx-HLS PGE Docker image for OPERA
# Author: Scott Collins

# Default SAS image path, must be provided by the docker build call via --build-arg
ARG SAS_IMAGE
FROM $SAS_IMAGE

ARG PGE_SOURCE_DIR
ARG PGE_DEST_DIR=/home/conda
ARG CONDA_ROOT=/opt/conda

ENV PGE_DEST_DIR=$PGE_DEST_DIR
ENV CONDA_ROOT=$CONDA_ROOT

ARG BUILD_DATE_TIME
ARG BUILD_VERSION

# labels
# the label-schema convention: http://label-schema.org/rc1/
LABEL org.label-schema.build-date=${BUILD_DATE_TIME} \
  org.label-schema.version=${BUILD_VERSION} \
  org.label-schema.license="Copyright 2022,\
 by the California Institute of Technology.\
 ALL RIGHTS RESERVED.\
 United States Government sponsorship acknowledged.\
 Any commercial use must be negotiated with the Office of Technology Transfer\
 at the California Institute of Technology.\
 This software may be subject to U.S. export control laws and regulations.\
 By accepting this document, the user agrees to comply with all applicable\
 U.S. export laws and regulations. User has the responsibility to obtain\
 export licenses, or other export authority as may be required, before\
 exporting such information to foreign countries or providing access to\
 foreign persons." \
  org.label-schema.name="OPERA Product Generation Executable (PGE) Image" \
  org.label-schema.schema-version="1.0" \
  org.label-schema.vendor="California Institute of Technology" \
  maintainer="California Institute of Technology"

# Copy the OPERA PGE software into the container
# the base container has a default user "conda" with UID/GID 1000/1000
COPY --chown=conda:conda ${PGE_SOURCE_DIR} ${PGE_DEST_DIR}

# Switch to root for installing into Conda Env
USER 0:0

# Install dependencies into existing Conda Env
# Modifications to the destination dir permissions are also required here to ensure
# we don't run into issues when running as an outside user (via docker run -u)
RUN set -ex \
    && cd ${PGE_DEST_DIR} \
    && mkdir -p ${CONDA_ROOT}/bin \
    && cp ${PGE_DEST_DIR}/opera/scripts/*_entrypoint.sh ${CONDA_ROOT}/bin \
    && chmod +x ${CONDA_ROOT}/bin/*_entrypoint.sh \
    && . ${CONDA_ROOT}/bin/activate root \
    && conda install --yes --channel conda-forge --file ${PGE_DEST_DIR}/opera/requirements.txt \
    && chmod 777 $(find ${PGE_DEST_DIR} -type d)

# Set the Docker entrypoint and clear the default command
ENTRYPOINT ["sh", "-c", "exec ${CONDA_ROOT}/bin/pge_docker_entrypoint.sh \"${@}\"", "--"]
CMD []

# Set the user/group back to the default
USER conda:conda

